### ISSUE TITLE
想问下这种json的path要怎么写

### ISSUE THREAD

**Issue by RainbowDashKira** [Q1351998764/nonebot-plugin-picture-api#2]
[{"id":"4MEAQffKS","url":"https://cdn2.thecatapi.com/images/4MEAQffKS.jpg","width":1250,"height":1167}]，试了下$.[url]和[url]，好像不能识别。

**Comment by Q1351998764** [comment]
哦，你可以更新一下，新版的这个插件不需要写path了，只写上图片接口就行了。

**Comment by Q1351998764** [comment]
而且你列表前面是不是有个键啊？比如说你接口返回的json总体是这样子？{"data":[{"id":"4MEAQffKS","url":"https://cdn2.thecatapi.com/images/4MEAQffKS.jpg","width":1250,"height":1167}]}
如果是这样的话，path就是data[0].url

**Comment by RainbowDashKira** [comment]
我是pip的看了一下是1.1。主要我发聊天指令他没反应，我就自己加了，我一开始直接写接口，他直接yml文件加载失败，插件也没加载成功。所以我才写path的。 我是用的这个api  里面没有data，我clone一下仓库再试试

**Comment by Q1351998764** [comment]
> 我是pip的看了一下是1.1。主要我发聊天指令他没反应，我就自己加了，我一开始直接写接口，他直接yml文件加载失败，插件也没加载成功。所以我才写path的。 我是用的这个api  里面没有data，我clone一下仓库再试试

哦哦，不好意思，我以为这插件没人用呢。。。所以我更新了指令动态添加之后一直没更新pip那边，我今晚回去就更新，直接clone仓库应该可以。

**Comment by RainbowDashKira** [comment]
没事，我的问题，我clone了一下可以用了，感谢解答。
