### ISSUE TITLE
这个有指令表吗？比如有查看所有关键词，删除图片接口等命令吗？

### ISSUE THREAD

**Issue by lintonxue00** [Q1351998764/nonebot-plugin-picture-api#3]
这个有指令表吗？比如有查看所有关键词，删除图片接口等命令吗？比如有个api失效了，怎么用命令删除，怎么查看当前有多少个关键词

**Comment by Q1351998764** [comment]
有指令表，如下："图片接口统计","图片接口","图片api统计","图片api"，这四个指令都可以查看所有关键词，但没有做命令删除的功能，只能手动去配置文件中删除。或者，你可以给同一个关键词添加多个api，只要有一个api有效，这个关键词就可以用。
